### ISSUE TITLE
Cannot register for Integration Credentials

### ISSUE THREAD

**Issue by AfricanBongo** [paynow/Paynow-Java-SDK#13]
The page from your link to create an Integration ID and key isn't working. May you please help.

**Comment by tzifudzi** [comment]
Thanks for notifying us @AfricanBongo. I have updated with the correct link in commit https://github.com/paynow/Paynow-Java-SDK/commit/f3a0a950a994f29b8625097d4e67df1f1a132b94. Please check again.

**Comment by AfricanBongo** [comment]
Thank you very much. @tzifudzi , looking forward to using your great library.
