### ISSUE TITLE
Payment not done for 10.0 amount

### ISSUE THREAD

**Issue by pervez8ktt** [paynow/Paynow-Java-SDK#4]
when we use payment.add("Banana",10.0)

it will return status error, Invalid amount 

the error is at 

Payment.java

public final HashMap<String, String> toDictionary()

method

map.put("amount", getTotal().setScale(2, BigDecimal.ROUND_HALF_UP).stripTrailingZeros().toString());

here this line changed amount to exponential

**Comment by pervez8ktt** [comment]
you can change 
map.put("amount", getTotal().setScale(2, BigDecimal.ROUND_HALF_UP).stripTrailingZeros().toString());

to


map.put("amount", getTotal().toString());

as your api already manage scale condition

**Comment by iammerus** [comment]
Hi @pervez8ktt. Thanks for letting us know about this.

**Comment by pervez8ktt** [comment]
One more thing we detect that you API not accept three digit payment i.e. 100 we assume that it is because of Test environment. Please let me know if we are wrong

**Comment by iammerus** [comment]
> One more thing we detect that you API not accept three digit payment i.e. 100 we assume that it is because of Test environment. Please let me know if we are wrong

Hi @pervez8ktt. The API does support 'three digit payments'. Can you walk me through the error you are facing?

**Comment by pervez8ktt** [comment]
> > One more thing we detect that you API not accept three digit payment i.e. 100 we assume that it is because of Test environment. Please let me know if we are wrong
> 
> Hi @pervez8ktt. The API does support 'three digit payments'. Can you walk me through the error you are facing?

I have made three digit payment using your sdk and into poll URL I have received status Awaiting+Delivery after completing payment.

**Comment by iammerus** [comment]
The Awaiting Delivery status is returned for buysafe merchants. You can read up more on the statuses here. https://developers.paynow.co.zw/docs/status_update.html 

Since the bug was fixed, I'm now closing this issue
