### ISSUE TITLE
Some Econet numbers regarded as invalid

### ISSUE THREAD

**Issue by tzifudzi** [paynow/Paynow-Java-SDK#7]
Econet phone numbers beginning with 0771, 0776, 0777 and 0778 are all matched as invalid numbers with the regex specified in the Paynow.java file. Note that numbers beginning with these digits exist.

Is this an intended requirement? Or can these numbers also perform mobile transactions.

**Comment by iammerus** [comment]
After going through the SDK, that seems to be a bug with the said regex. We might need to just remove that check since the Paynow API will return an error for invalid numbers.

**Comment by iammerus** [comment]
This was resolved in commit 4e4db6e
